TalkFlow-KR/TalkFlow-KR

server/app.js
server/config/config.json
server/controller/Cspeak.js
server/models/index.js
server/package-lock.json
server/package.json
server/routes/speak.js
server/test.js

npm i express sequelize mysql2

server setting

---

server/config/config.json
server/models/MSG.js
server/models/ROOM.js
server/models/USER.js
server/models/index.js

GPT DB의 USER,  ROOM, MSG 테이블 생성(외래키세팅 미적용)

DB setting

---

server/controller/Cspeak.js
server/routes/speak.js

router, controller set

---

server/app.js
server/controller/Cspeak.js
server/package-lock.json
server/package.json
server/routes/speak.js
server/views/index.ejs

feat: web-speech-api 추가

---

server/app.js
server/controller/Cspeak.js
server/models/index.js
server/package-lock.json
server/package.json
server/routes/speak.js

encryption password when user's inputs enter in database

encryption password

---

client/src/App.js
client/src/components/atoms/Button.jsx
client/src/components/atoms/Input.jsx
client/src/components/atoms/Title.jsx
client/src/components/molecules/LoginArticle.jsx
client/src/components/organisms/Header.jsx
client/src/components/organisms/Main.jsx
client/src/pages/MainPage.jsx
client/src/styles/App.css
client/src/styles/MainPage.styled.jsx

feat : MainPage 에 <CONTAINER> 추가

---

server/app.js
server/controller/Cspeak.js
server/controller/result.html
server/controller/test.html
server/models/MSG.js
server/models/ROOM.js
server/models/USER.js
server/models/index.js
server/routes/speak.js

1. 테스트를 위한 회원가입 및 로그인 임시 페이지 생성
2. 회원가입 및 로그인 기능 작동 확인

회원가입 및 로그인 구현 완료

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/molecules/NavArticle.jsx
client/src/components/organisms/Aside.jsx
client/src/components/organisms/Header.jsx
client/src/components/organisms/Main.jsx
client/src/pages/MainPage.jsx
client/src/styles/GlobalStyle.styled.jsx
client/src/styles/NavArticle.styled.jsx
client/src/styles/TopArticle.styled.jsx
client/src/styles/themeProvider/theme.js

create NavArticle.jsx / Aside.jsx / NavArticle.styled.jsx

feat : nav layout

---

server/app.js
server/controller/Cspeak.js
server/routes/speak.js
server/views/kakao.ejs

feat: kakao 간편 로그인 set

---

.gitignore
exercise/app.js
exercise/chatGPT.js
exercise/package-lock.json
exercise/package.json
exercise/views/index.ejs
server/models/USER.js
server/routes/speak.js

exercise 폴더 chat-gpt + whisper setting

feat: chat-gpt + whisper setting

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/molecules/InputWIthLabels.jsx
client/src/components/organisms/Auth/AuthForm.jsx
client/src/components/organisms/Auth/LoginForm.jsx
client/src/components/organisms/Auth/RegisterForm.jsx
client/src/pages/Register.jsx

 feat:회원가입페이지WIP

---

server/controller/Cspeak.js
server/models/USER.js
server/views/kakao.ejs

데이터베이스 수정 + id 값 말고, kakao nickname 값 불러오기로 변경

feat:kakao db set

---

server/app.js
server/controller/Cspeak.js
server/models/KAKAO.js
server/models/MSG.js
server/models/ROOM.js
server/models/USER.js
server/models/index.js
server/package-lock.json
server/package.json
server/routes/speak.js
server/views/kakao.ejs

1. 카카오 테이블 생성
2. 로그인한 사람 고유 ID 및 닉네임 DB 저장 확인
3. model/index 에서 외래키 지정, room 테이블에 kakaoId 칼럼 추가

add kakao table and check that functions

---

server/app.js
server/package-lock.json
server/package.json

feat: backend cors set

---

exercise/app.js
exercise/views/index.ejs

feat: whisper + gpt 구현완료

---

exercise/app.js
exercise/views/index.ejs

fixed: 사용되지 않는 코드 제거

---

exercise/views/index.ejs

feat:날짜&시간 추가

---

server/controller/Cspeak.js
server/models/MSG.js
server/models/ROOM.js

feat: date&time db 추가

---

server/controller/Cspeak.js

1. server 코드 수정(params, findOrCreate
2. react에서 axios 확인

modify server & check axios

---

client/public/index.html
client/src/App.js
client/src/components/atoms/KaKaoLogin.jsx
client/src/components/m/KaKaoLogin.jsx
client/src/components/organisms/Auth/KakaoAuth.jsx
client/src/components/organisms/Auth/RegisterForm.jsx

 kakao front test

---

client/src/App.js
client/src/components/organisms/Auth/LoginForm.jsx
client/src/components/organisms/Auth/RegisterForm.jsx
client/src/p/Index.jsx

회원가입에서 보내는 데이터 db상에서  not null 오류 뜸

 feat:login/register connect

---

client/src/components/organisms/Auth/LoginForm.jsx
client/src/components/organisms/Auth/RegisterForm.jsx

 modify:login form

---

gpt.sql
server/controller/Cgpt.js
server/controller/Cspeak.js
server/routes/speak.js

restful api 작명

---

client/src/App.js
client/src/components/o/CL.jsx
client/src/components/o/HW.jsx
client/src/components/o/HrC.jsx
client/src/components/o/Intro.jsx
client/src/components/o/MC.jsx
client/src/components/o/MW.jsx
exercise/.gitignore

feat: home,newchat,history 요소 display 수정

---

backendTestPlace/server/.gitignore
backendTestPlace/server/app.js
backendTestPlace/server/chatGPT.js
backendTestPlace/server/package-lock.json
backendTestPlace/server/package.json
backendTestPlace/server/views/index.ejs

feat: stt+tts 구현

---

backendTestPlace/server/app.js

feat: stt+tts

---

server/controller/Cspeak.js

send email

---

client/src/components/atoms/history.jsx
server/controller/Cgpt.js
server/controller/Cspeak.js

gpt prompt modify

---

client/src/App.js
client/src/components/atoms/KaKaoLogin.jsx
client/src/components/o/CR.jsx
client/src/components/organisms/Auth/RegisterForm.jsx
client/src/pages/Settings.jsx
gpt.sql
server/app.js
server/controller/Cgpt.js
server/controller/Cspeak.js
server/package-lock.json
server/package.json
server/routes/gpt.js
server/routes/speak.js
server/utils/Encrypt.js

1. 라우터 분리
2. 암호화 함수 분리
3. server part add .env

server part modify
